from google import genai
import os
from dotenv import load_dotenv
from rag_engine import retrieve_context
from agents import (
    upi_agent,
    credit_debit_agent,
    netbanking_agent,
    kyc_agent,
    loans_agent
)

load_dotenv()
client = genai.Client(api_key=os.getenv("GEMINI_API_KEY"))


# Safe Gemini response generator
def generate_response(prompt):
    response = client.models.generate_content(
        model="gemini-2.5-flash",
        contents=prompt
    )
    return response.text if hasattr(response, "text") else str(response)


# Step 1 — Classify domain using Gemini
def classify_domain(complaint: str) -> dict:
    prompt = f"""
You are a banking complaint classifier.
Classify this complaint into exactly ONE domain.

Domains: UPI, CreditDebit, NetBanking, KYC, Loans

Complaint: {complaint}

Return ONLY a JSON object like this:
{{
  "domain": "UPI",
  "confidence": 0.95,
  "severity": "Critical",
  "sentiment": "Very Angry",
  "priority": 9
}}
No explanation. Only valid JSON.
"""
    response_text = generate_response(prompt)

    import json, re

    try:
        json_match = re.search(r'\{.*\}', response_text, re.DOTALL)
        if json_match:
            return json.loads(json_match.group())
    except Exception as e:
        print("⚠️ JSON parsing failed:", e)

    # fallback
    return {
        "domain": "UPI",
        "confidence": 0.5,
        "severity": "Medium",
        "sentiment": "Neutral",
        "priority": 5
    }


# Step 2 — PII Masking
def mask_pii(text: str, customer_name: str) -> tuple:
    import re
    registry = {}
    counter = {"NAME": 0, "ACCT": 0, "PHONE": 0, "AMT": 0}

    # Mask amounts
    def replace_amount(m):
        counter["AMT"] += 1
        key = f"AMT_{counter['AMT']}"
        registry[key] = m.group()
        return f"[{key}]"

    # Mask phone numbers
    def replace_phone(m):
        counter["PHONE"] += 1
        key = f"PHONE_{counter['PHONE']}"
        registry[key] = m.group()
        return f"[{key}]"

    # Mask account numbers
    def replace_acct(m):
        counter["ACCT"] += 1
        key = f"ACCT_{counter['ACCT']}"
        registry[key] = m.group()
        return f"[{key}]"

    masked = re.sub(r'₹\s?\d+[\d,]*', replace_amount, text)
    masked = re.sub(r'Rs\.?\s?\d+[\d,]*', replace_amount, masked)
    masked = re.sub(r'\b\d{10}\b', replace_phone, masked)
    masked = re.sub(r'\b\d{9,18}\b', replace_acct, masked)

    # Mask customer name
    if customer_name:
        counter["NAME"] += 1
        key = f"NAME_{counter['NAME']}"
        masked = masked.replace(customer_name, f"[{key}]")
        registry[key] = customer_name

    return masked, registry


# Step 3 — Agent mapping
AGENT_MAP = {
    "UPI": upi_agent,
    "CreditDebit": credit_debit_agent,
    "NetBanking": netbanking_agent,
    "KYC": kyc_agent,
    "Loans": loans_agent
}

# Domain to vector store mapping
DOMAIN_TO_STORE = {
    "UPI": "upi",
    "CreditDebit": "credit_debit",
    "NetBanking": "netbanking",
    "KYC": "kyc",
    "Loans": "loans"
}


# Master orchestration function
def process_complaint(complaint: str,
                      customer_name: str,
                      vector_stores: dict) -> dict:

    print(f"\n{'='*50}")
    print(f"📥 Complaint received from: {customer_name}")
    print(f"{'='*50}")

    # Step 1 — Mask PII
    masked_complaint, registry = mask_pii(complaint, customer_name)
    print(f"🔐 PII Masked. Tokens: {list(registry.keys())}")

    # Step 2 — Classify domain
    classification = classify_domain(masked_complaint)
    domain = classification.get("domain", "UPI")
    confidence = classification.get("confidence", 0.5)
    print(f"🎯 Domain: {domain} | Confidence: {confidence}")

    # Step 3 — Confidence gate
    if confidence < 0.6:
        return {
            "status": "escalated",
            "reason": "Low classification confidence",
            "classification": classification,
            "message": "Complaint escalated to human agent for manual review."
        }

    # Step 4 — RAG retrieval
    store_key = DOMAIN_TO_STORE.get(domain, "upi")
    context = retrieve_context(vector_stores, store_key, masked_complaint)
    print(f"📚 RAG context retrieved for domain: {domain}")

    # Step 5 — Route to domain agent
    agent = AGENT_MAP.get(domain, upi_agent)

    try:
        result = agent.run(
            complaint=masked_complaint,
            context=context,
            customer_name=customer_name
        )
        print(f"✅ Response generated by: {result['agent']}")
    except Exception as e:
        print("❌ Agent failed:", e)
        return {
            "status": "error",
            "message": "AI agent failed. Escalating to human.",
            "error": str(e)
        }

    return {
        "status": "resolved",
        "customer_name": customer_name,
        "original_complaint": complaint,
        "masked_complaint": masked_complaint,
        "pii_registry": registry,
        "classification": classification,
        "rag_context_used": context,
        "agent_response": result["response"],
        "domain": domain
    }